### ISSUE TITLE
Client components support

### ISSUE THREAD

**Issue by PatrikTrefil** [Sprokets/nextjs-csp-report-only#1]
The solution stops working when you add client components. All script tags on the page that contains a client component stop getting the `nonce` attribute and the CSP blocks them. Is that a bug or intentional?

**Comment by danieltott** [comment]
@PatrikTrefil Well _that's_ not great 😬 

Can you paste in (or add a PR maybe?) of an example using a client component that's breaking? I'd love to dig in and see if we can get it working.

**Comment by PatrikTrefil** [comment]
Here are the steps to reproduce:

0. Open this repository
1. Create a new page with a simple client component.

```ts
// /app/page/page.tsx
import ClientComponent from "./client";

export default function Page() {
  return <ClientComponent />;
}
// /app/page/client.tsx
"use client";

export default function ClientComponent() {
  return <h1>I am a client component</h1>;
}
```

2. `npm run build`
3. `npm run start`
4. Navigate to `/page` and open the browser console. You should see many CSP errors.

It seems that any client component breaks it. Notice that the script tags in the served html do not contain the `nonce` attributes.

**Comment by PatrikTrefil** [comment]
Any updates on this?

**Comment by danieltott** [comment]
Hey @PatrikTrefil - the trick here isn't that it's using a client component, but that your example page is static. Currently the only way to have a useable CSP is with dynamic pages (since the `nonce` value needs to change every page load). 

If you force that page to be dynamic it works fine with the client component:

```tsx
import ClientComponent from './client';

export const dynamic = 'force-dynamic';

export default function Page() {
  return <ClientComponent />;
}
```

**Comment by PatrikTrefil** [comment]
Thanks for the response. I guess that makes sense. But, why do I not see this `force-dynamic` in your code here? How come your pages are dynamic even though you did not force this behavior?

**Comment by danieltott** [comment]
https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering

**Comment by PatrikTrefil** [comment]
Got it, thanks 👍
