### ISSUE TITLE
Localhost issues in page router

### ISSUE THREAD

**Issue by dippas** [Sprokets/nextjs-csp-report-only#3]
I've run your project locally and in the pages router I get this error:

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'report-sample' 'self' 'nonce-cd0a8ab1-f6b1-406e-ab83-8ebe74fd26fe'". Either the 'unsafe-inline' keyword, a hash ('sha256-4/2nIlfwIVTJ1+JcNQ6LkeVWzNS148LKAJeL5yofdN4='), or a nonce ('nonce-...') is required to enable inline execution.
`

which breaks the CSS. wondering why its not breaking in https://nextjs-csp-report-only.vercel.app/pages-router

![image](https://github.com/user-attachments/assets/c5d4c050-f808-4205-be04-1eb244d8d100)

Also there are a few other localhost errors that don't occur in your vercel deployment , such as:

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'report-sample' 'self' 'nonce-cd0a8ab1-f6b1-406e-ab83-8ebe74fd26fe' 'strict-dynamic'".`

`[Report Only] Refused to load the script 'http://localhost:3000/_next/static/chunks/webpack.js?v=1732193711540' because it violates the following Content Security Policy directive: "script-src 'report-sample' 'self' 'nonce-19b2b0ed-87c3-4bfc-87b3-3c7b5d4d06f3' 'strict-dynamic'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

For context I found this while having the same issue while trying to set a nonce in a nextjs application, and AFAIK it seems to be a limitation on nextjs https://github.com/vercel/next.js/discussions/54907 🤔

**Comment by danieltott** [comment]
@dippas I'll try to dig in to this - it's been a while since I've touched it. Just to confirm ahead of time - this is with no changes to the repo, simply clone -> npm install -> npm build -> npm start? Or is this in npm dev?

**Comment by dippas** [comment]
npm i > npm run dev

**Comment by danieltott** [comment]
OK - that's going to be a little different than what you see on vercel since that is basically after running `npm run start` -> give that a shot locally and see what's up?

**Comment by dippas** [comment]
ok with build & start works, why it does not work with dev ?

The report only errors still there tho
`
[Report Only] Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'report-sample' 'self' 'nonce-d403f488-1bff-4452-ab00-790abff81582' 'strict-dynamic'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

**Comment by danieltott** [comment]
So dev mode does a lot of extra stuff that production doesn't - like live reloads etc. You could probably modify the CSP to allow for that, but you'd have to use `unsafe-eval` etc. Not sure what's up on the report-only page
